# Configuration file for the Sphinx documentation builder.
# Auto-generated by fishertools DocumentationGenerator

project = 'test_project'
copyright = '2024, Auto-generated'
author = 'Auto-generated'
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode', 'sphinx.ext.napoleon', 'sphinx.ext.intersphinx']
templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
autodoc_default_options = {'members': True, 'undoc-members': True, 'show-inheritance': True}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}